"""add is_admin to users

Revision ID: 395ab095b09c
Revises: 4f8d9f0a6c21
Create Date: 2026-05-15 20:14:08.723942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395ab095b09c'
down_revision = '4f8d9f0a6c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
