"""add email verifications

Revision ID: afac34145495
Revises: 395ab095b09c
Create Date: 2026-05-18 22:19:02.377787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afac34145495'
down_revision = '395ab095b09c'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if 'email_verifications' in tables:
        indexes = {idx.get('name') for idx in inspector.get_indexes('email_verifications')}
        columns = {column.get('name') for column in inspector.get_columns('email_verifications')}
        indexed_column = 'email_hash' if 'email_hash' in columns else 'email'
        index_name = 'ix_email_verifications_email_hash' if indexed_column == 'email_hash' else 'ix_email_verifications_email'
        if index_name not in indexes:
            op.create_index(index_name, 'email_verifications', [indexed_column], unique=False)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email_verification_email')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if 'email_verifications' not in tables:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        indexes = {idx.get('name') for idx in inspector.get_indexes('email_verifications')}
        if 'ix_email_verifications_email' in indexes:
            batch_op.drop_index(batch_op.f('ix_email_verifications_email'))

    op.drop_table('email_verifications')
    # ### end Alembic commands ###
